version: '3'

tasks:
  run:
    vars:
      CFLAGS: '{{ default "-Wall -Wextra -Werror -ansi -pedantic" .CFLAGS }}'
      OUTPUT_FOLDER: '{{ default "bin" .OUTPUT_FOLDER }}'
    cmds:
      - task build OUTPUT_FOLDER='{{ .OUTPUT_FOLDER }}' CFLAGS='{{ .CFLAGS }}'
      - './{{ .OUTPUT_FOLDER }}/minesweeper.out'

  build:
    vars:
      CFLAGS: '{{ default "-Wall -Wextra -Werror -ansi -pedantic" .CFLAGS }}'
      OUTPUT_FOLDER: '{{ default "bin" .OUTPUT_FOLDER }}'
    cmds:
      - task build-linux OUTPUT_FOLDER='{{ .OUTPUT_FOLDER }}' CFLAGS='{{ .CFLAGS }}'
      - task build-windows OUTPUT_FOLDER='{{ .OUTPUT_FOLDER }}' CFLAGS='{{ .CFLAGS }}'
    silent: true

  build-linux:
    platforms: [linux]
    sources:
      - src/*.c
    vars:
      CFLAGS: '{{ default "-Wall -Wextra -Werror -ansi -pedantic" .CFLAGS }}'
      OUTPUT_FOLDER: '{{ default "bin" .OUTPUT_FOLDER }}'
    cmds:
      - mkdir -p '{{ .OUTPUT_FOLDER }}'
      - for: sources
        cmd: gcc {{ .CFLAGS }} {{ .ITEM }} -o "$(echo {{ .ITEM }} | sed -r 's/\.c$/\.o/' | sed 's/src/{{ .OUTPUT_FOLDER }}/')" -c
      - gcc {{ .CFLAGS }} -o '{{ .OUTPUT_FOLDER }}/minesweeper.out' $(find -type f -iwholename './{{ .OUTPUT_FOLDER }}/*.o' | xargs echo)
    generates:
      - '{{ .OUTPUT_FOLDER }}/minesweeper.out'
      - '{{ .OUTPUT_FOLDER }}/*.o'

  # Currently only works when running via Git Bash
  # If you're feeling like it, feel free to implement a powershell/cmd version as well!
  build-windows:
    platforms: [windows]
    sources:
      - src/*.c
    vars:
      CFLAGS: '{{ default "-Wall -Wextra -Werror -ansi -pedantic" .CFLAGS }}'
      OUTPUT_FOLDER: '{{ default "bin" .OUTPUT_FOLDER }}'
    cmds:
      - mkdir -p '{{ .OUTPUT_FOLDER }}'
      - for: sources
        cmd: gcc {{ .CFLAGS }} "$(echo '{{ .ITEM }}' | sed -r 's/\\/\//')" -o "$(echo '{{ .ITEM }}' | sed -r 's/\\/\//' | sed -r 's/\.c$/\.o/' | sed 's/src/{{ .OUTPUT_FOLDER }}/')" -c
      - gcc {{ .CFLAGS }} -o '{{ .OUTPUT_FOLDER }}/minesweeper.out' $(find . -type f -iwholename './{{ .OUTPUT_FOLDER }}/\*.o' | xargs echo)
    generates:
      - '{{ .OUTPUT_FOLDER }}/minesweeper.out'
      - '{{ .OUTPUT_FOLDER }}/*.o'
