name: ubuntu-run-unit-tests
on: [push]
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: install submodules
        run: git submodule update --init
      - name: install go-task
        run: sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b ~/.local/bin
      - name: task build
        run: task build
      - name: task test
        run: task test
